### ISSUE TITLE
如何贡献

### ISSUE THREAD

**Issue by genzj** [alivebao/clean-code-js#1]
Hello @alivebao ,

多谢你把这本书翻译成中文！不知你是否需要人协助，我可以帮你翻译一些。只是我尚不清楚应该如何贡献翻译，是否有工作流程我可以照做。另外原作者更新后你这边是如何同步的（我看这个repo不是fork过来的）？

谢谢！

**Comment by alivebao** [comment]
已经基本完成了翻译，同步的问题是我疏忽了，当时没有考虑到这些。现在watch了原项目，会不定期进行跟进。你有空的话也可以帮忙关注更新。另外我觉得也不一定要完全和原作一样，有好的想法咱们也可以自己提，欢迎fork:)

**Comment by genzj** [comment]
好的，谢谢！
