### ISSUE TITLE
Link to original project

### ISSUE THREAD

**Issue by ryanmcdermott** [alivebao/clean-code-js#4]
Can you link to my original project? Thank you! https://github.com/ryanmcdermott/clean-code-javascript

**Comment by alivebao** [comment]
In fact I have linked original project in my introduction:
![introduciton](https://cloud.githubusercontent.com/assets/8373285/22091530/31207612-de32-11e6-99cc-c6a12574fc4b.png)
And I will add the original link before the title later in order to clearer :)

**Comment by ryanmcdermott** [comment]
Awesome thank you!
